### ISSUE TITLE
Create Account: Error on exit

### ISSUE THREAD

**Issue by gagegage926** [rsanchez-wsu/RaiderPlanner#324] opened 2018-09-09 22:32 UTC
While on the create account window if a user decides to not go on further with the creation of there account, and uses the provided quit or the default close application button on windows an exception is thrown in UiManger.java -> createAccount().  A pop up is then generated alerting the user MainMenu.fxml does not exist. 

![errorgui](https://user-images.githubusercontent.com/5930101/45269562-2b3acf00-b45e-11e8-9db9-61f06a0bf867.PNG)

If the user has not created an account and is actively trying to exit the application should this error still be displayed? or just let them exit with out alerting them?  

**Stack Trace of said exception triggered, provided below for reference**

![errordebuglog](https://user-images.githubusercontent.com/5930101/45269567-50c7d880-b45e-11e8-8972-ad2d3fd44199.PNG)

**Comment by rsanchez-wsu** [comment] 2018-09-10 01:31
This looks like a dupe of #303.  However, that additional information provided by the stack trace is useful.  Please review #303, add anything from this issue that is not already in that issue, and then close this issue.

**Closed** 2018-09-11 13:30 UTC
Labels: duplicate
