### ISSUE TITLE
Quit from the Create New Account

### ISSUE THREAD

**Issue by AndrewVaughn** [rsanchez-wsu/RaiderPlanner#453] opened 2018-11-20 15:40 UTC
If you accidentally click on the New Profile item, you get the Create a New Account popup.  The issue here is that if you don't want to create a new account and click close, the program shuts down. That is the only option that the create new account offers. This could be resolved by have the New Profile "greyed out" so it is not active while you are in your profile. Another resolution would be to have a return or back button that would take you back to the previous screen. We could have a log out popup, that gives the choice of shutting  down or returning to our profile.

**Comment by Neon-Skyfire** [comment] 2018-11-20 19:48
This is being addressed in issue #406. My changes haven't been merged yet but I changed the quit button to a cancel button that takes the user back to the main program menu rather than quitting.

**Comment by rsanchez-wsu** [comment] 2018-11-22 16:29
Closing as a duplicate of #406.

**Closed by rsanchez-wsu** 2018-11-22 16:29 UTC
Labels: duplicate
